apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.service_slug}}
  namespace: demo-services
spec:
  selector:
    app: {{cookiecutter.service_slug}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{cookiecutter.container_port}}
